service: ${self:custom.subsys}-bff-service

provider:
  name: aws
  deploymentBucket: ${file(serverless/cfn.yml):deploymentBucket}
  # iam:
  # deploymentRole: ${file(serverless/cfn.yml):deploymentRole}
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:Query
      - dynamodb:GetItem
      - dynamodb:UpdateItem
      - dynamodb:PutItem
    Resource:
      - ${self:custom.tableArn}
  - Effect: Allow
    Action:
       - sqs:SendMessage
       - sqs:DeleteMessage
       - sqs:GetQueueAttributes
    Resource:
      - Fn::GetAtt: [ TriggerQueue, Arn ]
  - Effect: Allow
    Action:
      - sns:Publish
    Resource:
      - arn:aws:sns:us-west-2:167345660221:performance-service-bff-service-dev

  stackTags: ${file(serverless/tags.yml)}
  runtime: nodejs16.x
  logRetentionInDays: ${param:logRetentionInDays}
  environment: ${file(serverless/config.yml):environment}
  endpointType: REGIONAL
  # apiGateway: ${file(serverless/apig.yml):apiGateway}

params: ${file(serverless/config.yml):params}
custom: ${file(serverless/config.yml):custom}
package:
  individually: true

plugins:
  - serverless-aws-describe-plugin
  # - serverless-kinesis-esm-plugin
  # - serverless-secrets-mgr-plugin
  - serverless-webpack
  - baton-vcr-serverless-plugin
  - serverless-offline

functions:
  rest:
    handler: src/rest/index.handle
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: ${file(serverless/apig.yml):cors}
          # authorizer: ${file(serverless/apig.yml):authorizer}
  listener:
    handler: src/listener/index.handle
    events:
      - sqs:
          arn:
            Fn::GetAtt: [TriggerQueue, Arn]
        functionResponseType: ReportBatchItemFailures # reports messages in batches that failed to sqs
  trigger:
    handler: src/trigger/index.handle
    events:
      - stream:
          type: dynamodb
          arn: ${self:custom.tableStreamArn}
          batchSize: 100
          startingPosition: TRIM_HORIZON
          filterPatterns: ${file(serverless/dynamodb.yml):filterPatterns}
      # - sqs:
      #     arn:
      #       Fn::GetAtt: [ TriggerQueue, Arn ]

resources:
  - ${file(serverless/apig.yml):resources}
  # - ${file(serverless/sqs-listener.yml):resources}
  - ${file(serverless/dynamodb.yml):resources}
  # - ${file(serverless/s3.yml):resources}
  - ${file(serverless/sns.yml):resources}
  - ${file(serverless/sqs-trigger.yml):resources}
  # - ${file(serverless/secrets.yml):resources}
  - ${file(serverless/conditions.yml)}