resources:
  Resources:
    Topic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service}-dev
        # KmsMasterKeyId: alias/aws/sns
  Outputs:
    Topic:
      Value:
        Ref: Topic
      Export:
        Name: performance-service-topic-name
