resources:
  Resources:
    TriggerQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-dev-trigger
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [TriggerDLQ, Arn]
          maxReceiveCount: 1
    TriggerDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-dev-trigger-dlq
        # KmsMasterKeyId: alias/aws/sqs
        # https://stackoverflow.com/questions/63808647/aws-forward-event-bridge-event-to-encrypted-sqs-amazon-managed-key
    # TriggerQueuePolicy:
    #   Type: AWS::SQS::QueuePolicy
    #   Properties:
    #     Queues:
    #       - Ref: TriggerQueue
    #     PolicyDocument:
    #       Statement:
    #         - Effect: Allow
    #           Principal:
    #             Service: sns.amazonaws.com
    #           Action: sqs:SendMessage
    #           Resource:
    #             Fn::GetAtt: [TriggerQueue, Arn]
    #           Condition:
    #             ArnEquals:
    #               aws:SourceArn:
    #                 Ref: Topic
    SNSToTriggerQueue:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - Ref: TriggerQueue
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: sns.amazonaws.com # service that is allowed to perform the action
              Action: sqs:SendMessage # weird wording but allows a message to be sent to sqs
              Resource:
                Fn::GetAtt: [TriggerQueue, Arn]
              Condition:
                ArnEquals:
                  aws:SourceArn:
                    Ref: Topic

    QueueSubscriptionToTopic:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint:
          Fn::GetAtt: [ TriggerQueue, Arn ]
        TopicArn:
          Ref: Topic

  Outputs:
    TriggerQueue:
      Value:
        Ref: TriggerQueue
      Export:
        Name: TriggerQueue
    TriggerQueueArn:
      Value:
        Fn::GetAtt: [ TriggerQueue, Arn ]
      Export:
        Name: TriggerQueueArn
